# Generated by Django 5.2 on 2025-04-19 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_slug_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug_name',
            new_name='slug',
        ),
    ]
